"""initial schema

The whole data model of plan §5 in one revision: three enum types, twelve tables, four
indexes. One revision rather than twelve because there is no deployed database to
migrate — this is the schema the project starts with, and splitting it would produce a
history that tells a story that never happened.

Written by hand, not autogenerated. Autogenerate would have produced the same tables and
named half the constraints after Postgres defaults; `api/db_models/base.py` explains why
every name here is spelled out, and `test_migrations.py` asserts that this revision and
the ORM metadata describe the same database by requiring an empty `compare_metadata`
diff.

The enum types are created and dropped explicitly, and every column that uses one
declares `create_type=False`. Left at the default, the first `CREATE TABLE` referencing
a type would create it and the second would fail on a type that already exists.

Revision ID: 0001
Revises:
Created: 2026-08-30
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SESSION_MODE = postgresql.ENUM(
    "conversation", "read_aloud", name="session_mode", create_type=False
)
SESSION_STATUS = postgresql.ENUM(
    "active", "completed", "abandoned", name="session_status", create_type=False
)
ATTEMPT_STATUS = postgresql.ENUM(
    "pending", "scoring", "scored", "failed", name="attempt_status", create_type=False
)


def upgrade() -> None:
    bind = op.get_bind()
    for enum in (SESSION_MODE, SESSION_STATUS, ATTEMPT_STATUS):
        enum.create(bind, checkfirst=False)

    # ── Accounts and content ────────────────────────────────────────────────

    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("native_language", sa.Text(), server_default="es", nullable=False),
        sa.Column("cefr_self_assessed", sa.Text(), nullable=True),
        sa.Column("retain_audio", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    op.create_table(
        "scenarios",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("cefr_band", sa.Text(), nullable=False),
        sa.Column("persona_prompt", sa.Text(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column(
            "target_grammar",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "target_functions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "rubric",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_scenarios"),
        sa.UniqueConstraint("slug", name="uq_scenarios_slug"),
    )

    op.create_table(
        "passages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("cefr_band", sa.Text(), nullable=False),
        sa.Column(
            "phoneme_focus",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_passages"),
        sa.UniqueConstraint("slug", name="uq_passages_slug"),
    )

    op.create_table(
        "audio_assets",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("format", sa.Text(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("device_hint", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_audio_assets_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_audio_assets"),
        sa.UniqueConstraint("user_id", "sha256", name="uq_audio_assets_user_id_sha256"),
    )

    # ── Practice ────────────────────────────────────────────────────────────

    op.create_table(
        "sessions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("scenario_id", sa.BigInteger(), nullable=True),
        sa.Column("mode", SESSION_MODE, nullable=False),
        sa.Column("status", SESSION_STATUS, server_default="active", nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
            name="fk_sessions_scenario_id_scenarios",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_sessions_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_sessions"),
    )
    op.create_index(
        "ix_sessions_user_id_started_at", "sessions", ["user_id", "started_at"]
    )

    op.create_table(
        "turns",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("audio_asset_id", sa.BigInteger(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("words", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("asr_confidence", sa.Float(), nullable=True),
        sa.Column("asr_model", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('user', 'assistant')", name="ck_turns_role"),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"],
            ["audio_assets.id"],
            name="fk_turns_audio_asset_id_audio_assets",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name="fk_turns_session_id_sessions",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_turns"),
        sa.UniqueConstraint("session_id", "idx", name="uq_turns_session_id_idx"),
    )

    op.create_table(
        "attempts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("passage_id", sa.BigInteger(), nullable=False),
        sa.Column("audio_asset_id", sa.BigInteger(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("wer", sa.Float(), nullable=True),
        sa.Column("status", ATTEMPT_STATUS, server_default="pending", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"],
            ["audio_assets.id"],
            name="fk_attempts_audio_asset_id_audio_assets",
        ),
        sa.ForeignKeyConstraint(
            ["passage_id"], ["passages.id"], name="fk_attempts_passage_id_passages"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name="fk_attempts_session_id_sessions",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_attempts"),
    )

    # ── Measurement ─────────────────────────────────────────────────────────

    op.create_table(
        "fluency_metrics",
        sa.Column("turn_id", sa.BigInteger(), nullable=False),
        sa.Column("speech_rate_wpm", sa.Float(), nullable=True),
        sa.Column("articulation_rate", sa.Float(), nullable=True),
        sa.Column("pause_ratio", sa.Float(), nullable=True),
        sa.Column("mean_length_run", sa.Float(), nullable=True),
        sa.Column("filler_count", sa.Integer(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("response_latency_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["turns.id"],
            name="fk_fluency_metrics_turn_id_turns",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("turn_id", name="pk_fluency_metrics"),
    )

    op.create_table(
        "grammar_usage",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("turn_id", sa.BigInteger(), nullable=False),
        sa.Column("feature", sa.Text(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["turns.id"],
            name="fk_grammar_usage_turn_id_turns",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_grammar_usage"),
        sa.UniqueConstraint(
            "turn_id", "feature", name="uq_grammar_usage_turn_id_feature"
        ),
    )

    op.create_table(
        "language_errors",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("turn_id", sa.BigInteger(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("subcategory", sa.Text(), nullable=True),
        sa.Column("span_start", sa.Integer(), nullable=True),
        sa.Column("span_end", sa.Integer(), nullable=True),
        sa.Column("original", sa.Text(), nullable=False),
        sa.Column("correction", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("detector", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "detector IN ('llm', 'rule')", name="ck_language_errors_detector"
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["turns.id"],
            name="fk_language_errors_turn_id_turns",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_language_errors"),
    )
    op.create_index(
        "ix_language_errors_turn_id_category",
        "language_errors",
        ["turn_id", "category"],
    )

    op.create_table(
        "phoneme_scores",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("attempt_id", sa.BigInteger(), nullable=False),
        sa.Column("word", sa.Text(), nullable=False),
        sa.Column("word_idx", sa.Integer(), nullable=False),
        sa.Column("phone_idx", sa.Integer(), nullable=False),
        sa.Column("canonical_phone", sa.Text(), nullable=False),
        sa.Column("recognized_phone", sa.Text(), nullable=True),
        sa.Column("start_ms", sa.Integer(), nullable=True),
        sa.Column("end_ms", sa.Integer(), nullable=True),
        sa.Column("gop", sa.Float(), nullable=False),
        sa.Column("posterior", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name="fk_phoneme_scores_attempt_id_attempts",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_phoneme_scores"),
    )
    op.create_index("ix_phoneme_scores_attempt_id", "phoneme_scores", ["attempt_id"])
    op.create_index(
        "ix_phoneme_scores_canonical_phone", "phoneme_scores", ["canonical_phone"]
    )

    op.create_table(
        "progress_snapshots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("period", sa.Text(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column(
            "fluency",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "accuracy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "complexity",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "pronunciation",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "sample_counts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("cefr_estimate", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "period IN ('day', 'week')", name="ck_progress_snapshots_period"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_progress_snapshots_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_progress_snapshots"),
        sa.UniqueConstraint(
            "user_id",
            "period",
            "period_start",
            name="uq_progress_snapshots_user_id_period_period_start",
        ),
    )


def downgrade() -> None:
    """Reverse order, then the types.

    A downgrade that leaves the enum types behind is the migration bug that only shows
    up on the *second* `upgrade head` — as `type "session_mode" already exists`, several
    minutes after the mistake was made. test_migrations.py runs up, down and up again on
    a scratch database for exactly that reason.
    """
    op.drop_table("progress_snapshots")
    op.drop_index("ix_phoneme_scores_canonical_phone", table_name="phoneme_scores")
    op.drop_index("ix_phoneme_scores_attempt_id", table_name="phoneme_scores")
    op.drop_table("phoneme_scores")
    op.drop_index("ix_language_errors_turn_id_category", table_name="language_errors")
    op.drop_table("language_errors")
    op.drop_table("grammar_usage")
    op.drop_table("fluency_metrics")
    op.drop_table("attempts")
    op.drop_table("turns")
    op.drop_index("ix_sessions_user_id_started_at", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("audio_assets")
    op.drop_table("passages")
    op.drop_table("scenarios")
    op.drop_table("users")

    bind = op.get_bind()
    for enum in (ATTEMPT_STATUS, SESSION_STATUS, SESSION_MODE):
        enum.drop(bind, checkfirst=False)
