"""The declarative base, and the constraint naming convention.

The naming convention is the load-bearing part. Postgres will happily name a constraint
for you, and SQLAlchemy will happily name it differently — at which point
`alembic revision --autogenerate` emits a drop-and-recreate for a constraint that
never changed, because the only difference is what it is called. Fixing the names once,
here, is what makes every later autogenerated revision honest.

Every name in `0001_initial_schema.py` is written out in full to match these patterns.
`test_migrations.py` asserts the two agree by running Alembic's own metadata comparison
against the migrated database and requiring an empty diff, so a mismatch is a red test
rather than a surprise in the next migration.
"""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
